import Nav from '@/components/nav';
import '../styles/globals.css';
import '../styles/globals.scss';
import Footer from '@/components/footer';
import { ThemeProvider } from '@/components/theme/provider';
import { Analytics } from '@vercel/analytics/react';
import type { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <Nav />
          {children}
          <Analytics mode={'production'} />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
